package com.example.databasetools;

import com.intellij.database.model.DasColumn;
import com.intellij.database.util.DasUtil;
import lombok.Getter;

@Getter
public class Column {

    private final String name;
    private final String comment;
    private final boolean isNotNull;
    private final boolean isAutoGenerated;
    private final boolean isPrimaryKey;

    public Column(DasColumn column) {
        this.name = column.getName();
        comment = column.getComment();
        isNotNull = column.isNotNull();
        isAutoGenerated = DasUtil.isAutoGenerated(column);
        isPrimaryKey = DasUtil.isPrimary(column);
    }

    @Override
    public String toString() {
        return "Column{" +
            "name='" + name + '\'' +
            ", comment='" + comment + '\'' +
            ", isNotNull=" + isNotNull +
            ", isAutoGenerated=" + isAutoGenerated +
            ", isPrimaryKey=" + isPrimaryKey +
            '}';
    }
}
